### ISSUE TITLE
perf/perf.go:101:10: assignment mismatch: 2 variables but 3 values

### ISSUE THREAD

**Issue by nim-nim** [couchbase/go-couchbase#86]
perf does not build with Go 1.10 x86_64
```
cd /builddir/build/BUILD/go-couchbase-a064ca416844fb169255a76fbdac7e80101b6049/_build/src/github.com/couchbase/go-couchbase/perf
/usr/lib/golang/pkg/tool/linux_amd64/compile -o $WORK/b001/_pkg_.a -trimpath $WORK/b001 -shared -p main -complete -installsuffix shared -bui
ldid xg8dqXZtFmAoDE_d3Yjw/xg8dqXZtFmAoDE_d3Yjw -goversion go1.10 -D "" -importcfg $WORK/b001/importcfg -pack ./generate-json.go ./perf.go
# github.com/couchbase/go-couchbase/perf
perf/perf.go:101:10: assignment mismatch: 2 variables but 3 values
perf/perf.go:101:22: not enough arguments in call to b.GetBulk
        have ([]string)
        want ([]string, time.Time, []string)
error: Bad exit status from /var/tmp/rpm-tmp.tCh9vC (%build)
```
